/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PostImport } from './routes/post'
import { Route as FormImport } from './routes/form'
import { Route as IndexImport } from './routes/index'
import { Route as CollectionCategoryImport } from './routes/collection.$category'

// Create/Update Routes

const PostRoute = PostImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRoute,
} as any)

const FormRoute = FormImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CollectionCategoryRoute = CollectionCategoryImport.update({
  id: '/collection/$category',
  path: '/collection/$category',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormImport
      parentRoute: typeof rootRoute
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostImport
      parentRoute: typeof rootRoute
    }
    '/collection/$category': {
      id: '/collection/$category'
      path: '/collection/$category'
      fullPath: '/collection/$category'
      preLoaderRoute: typeof CollectionCategoryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form': typeof FormRoute
  '/post': typeof PostRoute
  '/collection/$category': typeof CollectionCategoryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form': typeof FormRoute
  '/post': typeof PostRoute
  '/collection/$category': typeof CollectionCategoryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/form': typeof FormRoute
  '/post': typeof PostRoute
  '/collection/$category': typeof CollectionCategoryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/form' | '/post' | '/collection/$category'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/form' | '/post' | '/collection/$category'
  id: '__root__' | '/' | '/form' | '/post' | '/collection/$category'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormRoute: typeof FormRoute
  PostRoute: typeof PostRoute
  CollectionCategoryRoute: typeof CollectionCategoryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormRoute: FormRoute,
  PostRoute: PostRoute,
  CollectionCategoryRoute: CollectionCategoryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/form",
        "/post",
        "/collection/$category"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/form": {
      "filePath": "form.tsx"
    },
    "/post": {
      "filePath": "post.tsx"
    },
    "/collection/$category": {
      "filePath": "collection.$category.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
